name: Build and Push DevContainer

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/build-and-push-devcontainer.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker container
              uses: docker/build-push-action@v6
              with:
                  context: ./devcontainer
                  file: .devcontainer/Dockerfile
                  push: true
                  tags: |
                      bernedom/qtandroidbuilder:latest
                      bernedom/qtandroidbuilder:${{ github.sha }}


